api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

middlewares:
  retry:
    retry:
      attempts: 3
      initialInterval: 500ms

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: nextgen_nw

entryPoints:
  web:
    address: ":80"



  